#
# Module manifest for module 'GR-Telemetry'
#
# Generated by: Cloud Security Compliance Team
#
# Contact Information for module : cloudsecuritycompliance-conformiteinfonuagiquesecurise@ssc-spc.gc.ca
#
# Generated on: 2025-10-08
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GR-Telemetry'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '5b3f5f4d-3a31-44e4-9a73-25da7c571d5d'

# Author of this module
Author = 'Cloud Security Compliance'

# Company or vendor of this module
CompanyName = 'Shared Services Canada'

# Copyright statement for this module
Copyright = ''

# Description of the functionality provided by this module
Description = 'Shared telemetry helpers for Guardrails runbooks.'

# Functions to export from this module.
FunctionsToExport = '*'

# Cmdlets to export from this module.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module.
AliasesToExport = '*'

PrivateData = @{
    PSData = @{
        Tags = 'GOC 30 days Guardrails'
    }
}

}